#ifndef __ARB_API__
#define __ARB_API__


#define ARB_GENL_FAMILY_NAME 	"arb_api"
#define ARB_GENL_FAMILY_VERSION	0x01

enum {
	ARB_GENL_CMD_UNSPEC,
	ARB_GENL_CMD_SET_SERVICE,
	ARB_GENL_CMD_SET_MAP,
	__ARB_GENL_CMD_MAX
};
#define ARB_GENL_CMD_MAX (__ARB_GENL_CMD_MAX - 1)


enum {
	ARB_GENL_ATTR_UNSPEC,
	ARB_GENL_ATTR_MARK,
	ARB_GENL_ATTR_FD,
	ARB_GENL_ATTR_SERVICE_NAME,
	__ARB_GENL_ATTR_MAX
};
#define ARB_GENL_ATTR_MAX (__ARB_GENL_ATTR_MAX - 1)

#endif
